version: "2"
linters:
  default: all
  disable:
    - copyloopvar
    - err113
    - exhaustruct
    - gochecknoglobals
    - godot
    - godox
    - intrange
    - lll
    - mnd
    - nlreturn
    - paralleltest
    - testifylint
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: 100
      statements: 60
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/michurin/cnbot
            - golang.org/x/sync/errgroup
            - github.com/michurin/systemd-env-file
            - github.com/stretchr/testify
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
        path: pkg/app/(log|version).go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/michurin/cnbot)

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
