linters-settings:
  lll:
    line-length: 160
  funlen:
    lines: 120
    statements: 60
  nakedret:
    max-func-lines: 100
  cyclop:
    max-complexity: 16
  gci:
    local-prefixes: github.com/michurin/cnbot
linters:
  disable-all: true
  enable:
    - bodyclose
      # - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
      # disabled by default
      # TODO: check desabled
    - asciicheck
    - cyclop
    - durationcheck
      # - errorlint
      # - exhaustivestruct
      # - forbidigo
    - forcetypeassert
    - gci
      # - gochecknoglobals
      # - gochecknoinits
    - gocognit
      # - godot
      # - godox
      # - goerr113
    - gofumpt
    - goheader
      # - gomnd
    - gomoddirectives
    - gomodguard
      # - ifshort
    - importas
    - makezero
      # - maligned
    - nestif
    - nilerr
      # - nlreturn
      # - paralleltest
    - prealloc
    - predeclared
    - revive
    - sqlclosecheck
      # - testpackage
    - thelper
      # - tparallel
    - wastedassign
      # - wrapcheck
      # - wsl
