version: "2"
linters:
  default: all
  disable:
    - copyloopvar
    - err113
    - exhaustruct
    - gochecknoglobals
    - godot
    - godox
    - intrange
    - lll
    - mnd
    - nlreturn
    - paralleltest
    - revive
    - testifylint
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: 100
      statements: 60
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/michurin/cnbot
            - github.com/michurin/systemd-env-file
            - github.com/stretchr/testify
            - golang.org/x/sync/errgroup
  exclusions:
    generated: lax
    warn-unused: true
    rules:
      - path: "pkg/app/(log|version)\\.go"
        linters:
          - forbidigo
      - source: "^\\s*defer\\s+"
        linters:
          - errcheck
      - source: "\\s(os\\.ReadFile|exec\\.Command)\\("
        linters:
          - gosec
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/michurin/cnbot)
