name: build

on:
  - push
  - pull_request

jobs:

  build:
    name: Build
    strategy:
      matrix:
        go:
          - 1.14.x
          - 1.20.x
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v ./cmd/...
